[package]
name = "riscv-demo"
version = "0.1.0"
authors = ["Ettore Del Negro <ettore@ettoredelnegro.me>"]
edition = "2018"

[dependencies]
riscv-rt = "0.6.1"
panic-halt = "0.2.0"

[[bin]]
name = "riscv-demo"
test = false
bench = false
