MEMORY
{
  RAM : ORIGIN = 0x80000000, LENGTH = 1024M /* see DRAM_BASE at https://github.com/riscv/riscv-isa-sim/blob/master/riscv/encoding.h */
  FLASH : ORIGIN = 0x20000000, LENGTH = 1K /* ?? spike -m0x20000000:1024 */
}

REGION_ALIAS("REGION_TEXT", RAM);
REGION_ALIAS("REGION_RODATA", RAM);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_HEAP", RAM);
REGION_ALIAS("REGION_STACK", RAM);
